# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [2]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [3]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

['4.5' 'top' 'top' 'top' '4.5' 'top' 'top' 'bottom' '4.5' 'top']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [4]:
# Місце для Вашого коду
number=np.arange(0, 10, 1)
print(number)
print(np.random.choice(number, size=1, replace=False))

[0 1 2 3 4 5 6 7 8 9]
[4]


Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [5]:
# Місце для Вашого коду
number=np.arange(0, 10, 1)
print(number)
mas=(np.random.choice(number, size=24, replace=True))
mas.shape=(4,6)
print(mas)


[0 1 2 3 4 5 6 7 8 9]
[[0 0 1 9 2 1]
 [7 0 2 5 0 7]
 [7 9 9 0 4 2]
 [7 2 9 4 5 6]]


### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [6]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[3 4 3 4 1 4 3 2 4 2]


Згенеруйте одну випадкову цифру.

In [7]:
# Місце для Вашого коду
low = 0
high = 10
size = 1
print(np.random.randint(low=low, high=high, size=size))


[1]


Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [8]:
# Місце для Вашого коду
# Місце для Вашого коду
low = 0
high = 10
size = (4,5)
print(np.random.randint(low=low, high=high, size=size))


[[4 4 4 7 8]
 [7 8 3 7 8]
 [2 5 8 8 3]
 [8 3 8 2 2]]


### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [9]:
size = None
print(np.random.sample(size=size))

0.536570433701858


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [10]:
# Місце для Вашого коду
size=(3,4)
print(np.random.sample(size=size))

[[0.99125452 0.8887628  0.09932261 0.87527534]
 [0.19247901 0.95532177 0.40720097 0.52499522]
 [0.01660515 0.60110307 0.92378267 0.98538943]]


Згенеруйте 10 випадкових чисел з інтервалу $[a, b)$.

In [11]:
a = 3
b = 5

In [12]:
# Місце для Вашого коду
size=10
k=2*np.random.sample(size=size)+3
print(k)


[4.59599185 4.76650788 3.87017464 3.36864677 4.65179989 4.83068631
 3.6438862  4.50408368 4.68621769 3.7079893 ]


### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [13]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[6 4 3 9 2 7 0 1 8 5]


Перетасуйте матрицю $M$.

In [14]:
M = np.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [15]:
# Місце для Вашого коду
np.random.shuffle(M)
#print(M)
Mt=np.transpose(M) 
np.random.shuffle(Mt)
print(Mt)

[[13 18  3  8]
 [10 15  0  5]
 [11 16  1  6]
 [14 19  4  9]
 [12 17  2  7]]


## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [16]:
np.random.seed(42)

In [17]:
print(np.random.randint(10))

6


In [18]:
print(np.random.randint(10))

3


In [19]:
np.random.seed(42)
print(np.random.randint(10))
np.random.seed(42)
print(np.random.randint(10))


6
6


In [20]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [21]:
p=0.5
n=10
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['H' 'H' 'H' 'H' 'T' 'H' 'H' 'T' 'H' 'H']


In [22]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

8 heads and 2 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [23]:
# Місце для Вашого коду
p=0.5
n=100
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

['H' 'H' 'T' 'H' 'T' 'T' 'H' 'T' 'H' 'H' 'T' 'T' 'T' 'H' 'H' 'T' 'H' 'H'
 'H' 'H' 'T' 'H' 'T' 'H' 'T' 'T' 'H' 'T' 'T' 'T' 'T' 'T' 'T' 'H' 'H' 'H'
 'H' 'H' 'H' 'T' 'H' 'H' 'T' 'H' 'T' 'H' 'T' 'T' 'H' 'H' 'T' 'T' 'T' 'T'
 'H' 'H' 'H' 'T' 'T' 'H' 'H' 'H' 'H' 'T' 'T' 'T' 'H' 'H' 'T' 'T' 'T' 'T'
 'H' 'T' 'H' 'H' 'H' 'H' 'T' 'H' 'T' 'T' 'H' 'H' 'T' 'H' 'H' 'H' 'H' 'T'
 'T' 'T' 'T' 'T' 'H' 'T' 'T' 'T' 'T' 'H']
50 heads and 50 tails


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [24]:
# Місце для Вашого коду
low = 0
high = 2
size = 100
a=(np.random.randint(low=low, high=high, size=size))
print(a)
heads = list(a).count(0)
tails = list(a).count(1)

print("{} heads and {} tails".format(heads,tails))

[0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1 1 1 0 1 0 1 0 1 1 1 1
 0 1 0 0 0 0 1 0 0 0 1 1 1 1 0 0 1 0 0 0 1 1 0 1 1 1 1 1 0 1 0 0 1 0 0 0 1
 1 0 1 1 1 1 0 0 1 1 0 0 1 0 1 1 0 0 1 1 0 1 0 1 0 0]
51 heads and 49 tails


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [25]:
# Місце для Вашого коду
size =100
import numpy as np
a=(np.random.sample(size=size))

print(a)
#b=a>0.5
#print(b)
def f (a):
   if a>0.5:
        c='H'
   else:
        c='T'
   return(c)
f1=np.vectorize(f)
print(f1(a))

[0.22649578 0.64517279 0.17436643 0.69093774 0.38673535 0.93672999
 0.13752094 0.34106635 0.11347352 0.92469362 0.87733935 0.25794163
 0.65998405 0.8172222  0.55520081 0.52965058 0.24185229 0.09310277
 0.89721576 0.90041806 0.63310146 0.33902979 0.34920957 0.72595568
 0.89711026 0.88708642 0.77987555 0.64203165 0.08413996 0.16162871
 0.89855419 0.60642906 0.00919705 0.10147154 0.66350177 0.00506158
 0.16080805 0.54873379 0.6918952  0.65196126 0.22426931 0.71217922
 0.23724909 0.3253997  0.74649141 0.6496329  0.84922341 0.65761289
 0.5683086  0.09367477 0.3677158  0.26520237 0.24398964 0.97301055
 0.39309772 0.89204656 0.63113863 0.7948113  0.50263709 0.57690388
 0.49251769 0.19524299 0.72245212 0.28077236 0.02431597 0.6454723
 0.17711068 0.94045858 0.95392858 0.91486439 0.3701587  0.01545662
 0.92831856 0.42818415 0.96665482 0.96361998 0.85300946 0.29444889
 0.38509773 0.85113667 0.31692201 0.16949275 0.55680126 0.93615477
 0.6960298  0.57006117 0.09717649 0.61500723 0.99005385 0.14008

### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [26]:
# Місце для Вашого коду
low = 0
high = 2
list6=[10,50,100,250,500,1000,2500,5000,10000]
for i in list6:
    size = i
    a=(np.random.randint(low=low, high=high, size=size))
    #print(a)
    heads = list(a).count(0)
    tails = list(a).count(1)
    print(i, tails/(heads+tails))
    



10 0.5
50 0.6
100 0.54
250 0.452
500 0.492
1000 0.473
2500 0.5084
5000 0.497
10000 0.5003


## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [27]:
# Місце для Вашого коду
low = 1
high = 7
size = 100
a=(np.random.randint(low=low, high=high, size=size))
print(a)
d=dict()
for i in range (1, 7):
    d_= list(a).count(i)
    d.update({i:d_})


print(d)

[3 4 4 4 6 1 3 6 3 6 6 1 3 6 1 2 5 6 4 1 1 6 1 2 1 5 5 4 2 5 6 3 3 3 6 1 6
 1 3 4 4 1 3 6 4 1 6 3 2 3 3 6 6 5 5 6 6 2 2 3 4 2 3 1 5 4 3 6 1 5 1 3 2 5
 1 2 4 3 3 5 1 4 6 5 6 5 1 4 1 3 6 2 3 3 6 5 3 4 3 4]
{1: 18, 2: 10, 3: 23, 4: 15, 5: 13, 6: 21}


### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [28]:
# Місце для Вашого коду
low = 0
high = 7
list7=[10,50,100,250,500,1000,2500,5000,10000]
for i in list7:
    size = i
    a=(np.random.randint(low=low, high=high, size=size))
    d=dict()
    probability={}
    for j in range (1, 7):
        d_= list(a).count(j)
        d.update({j:d_})
        d_p=d_/i
        probability.update({j:d_p})
    print(d, probability)


{1: 1, 2: 1, 3: 3, 4: 3, 5: 0, 6: 1} {1: 0.1, 2: 0.1, 3: 0.3, 4: 0.3, 5: 0.0, 6: 0.1}
{1: 9, 2: 7, 3: 6, 4: 8, 5: 7, 6: 9} {1: 0.18, 2: 0.14, 3: 0.12, 4: 0.16, 5: 0.14, 6: 0.18}
{1: 11, 2: 9, 3: 16, 4: 5, 5: 21, 6: 19} {1: 0.11, 2: 0.09, 3: 0.16, 4: 0.05, 5: 0.21, 6: 0.19}
{1: 35, 2: 38, 3: 41, 4: 45, 5: 23, 6: 33} {1: 0.14, 2: 0.152, 3: 0.164, 4: 0.18, 5: 0.092, 6: 0.132}
{1: 63, 2: 67, 3: 72, 4: 58, 5: 90, 6: 78} {1: 0.126, 2: 0.134, 3: 0.144, 4: 0.116, 5: 0.18, 6: 0.156}
{1: 163, 2: 135, 3: 150, 4: 136, 5: 144, 6: 138} {1: 0.163, 2: 0.135, 3: 0.15, 4: 0.136, 5: 0.144, 6: 0.138}
{1: 360, 2: 321, 3: 348, 4: 364, 5: 344, 6: 414} {1: 0.144, 2: 0.1284, 3: 0.1392, 4: 0.1456, 5: 0.1376, 6: 0.1656}
{1: 731, 2: 705, 3: 675, 4: 697, 5: 728, 6: 737} {1: 0.1462, 2: 0.141, 3: 0.135, 4: 0.1394, 5: 0.1456, 6: 0.1474}
{1: 1421, 2: 1398, 3: 1504, 4: 1427, 5: 1417, 6: 1450} {1: 0.1421, 2: 0.1398, 3: 0.1504, 4: 0.1427, 5: 0.1417, 6: 0.145}


## 5 Колода карт
### 5.1 Реалізація

In [29]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)

[('5', '♠'), ('5', '♡'), ('5', '♢'), ('5', '♣'), ('7', '♠'), ('7', '♡'), ('7', '♢'), ('7', '♣'), ('10', '♠'), ('10', '♡'), ('10', '♢'), ('10', '♣'), ('2', '♠'), ('2', '♡'), ('2', '♢'), ('2', '♣'), ('4', '♠'), ('4', '♡'), ('4', '♢'), ('4', '♣'), ('Q', '♠'), ('Q', '♡'), ('Q', '♢'), ('Q', '♣'), ('8', '♠'), ('8', '♡'), ('8', '♢'), ('8', '♣'), ('K', '♠'), ('K', '♡'), ('K', '♢'), ('K', '♣'), ('J', '♠'), ('J', '♡'), ('J', '♢'), ('J', '♣'), ('9', '♠'), ('9', '♡'), ('9', '♢'), ('9', '♣'), ('1', '♠'), ('1', '♡'), ('1', '♢'), ('1', '♣'), ('3', '♠'), ('3', '♡'), ('3', '♢'), ('3', '♣'), ('6', '♠'), ('6', '♡'), ('6', '♢'), ('6', '♣')]


In [30]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

5♠, 5♡, 5♢, 5♣, 7♠, 7♡, 7♢, 7♣, 10♠, 10♡, 10♢, 10♣, 2♠, 2♡, 2♢, 2♣, 4♠, 4♡, 4♢, 4♣, Q♠, Q♡, Q♢, Q♣, 8♠, 8♡, 8♢, 8♣, K♠, K♡, K♢, K♣, J♠, J♡, J♢, J♣, 9♠, 9♡, 9♢, 9♣, 1♠, 1♡, 1♢, 1♣, 3♠, 3♡, 3♢, 3♣, 6♠, 6♡, 6♢, 6♣


In [31]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♠5, ♠7, ♠10, ♠2, ♠4, ♠Q, ♠8, ♠K, ♠J, ♠9, ♠1, ♠3, ♠6
♡5, ♡7, ♡10, ♡2, ♡4, ♡Q, ♡8, ♡K, ♡J, ♡9, ♡1, ♡3, ♡6
♢5, ♢7, ♢10, ♢2, ♢4, ♢Q, ♢8, ♢K, ♢J, ♢9, ♢1, ♢3, ♢6
♣5, ♣7, ♣10, ♣2, ♣4, ♣Q, ♣8, ♣K, ♣J, ♣9, ♣1, ♣3, ♣6


In [32]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('6', '♣'), ('7', '♢'), ('7', '♡'), ('3', '♣'), ('K', '♣'), ('2', '♠'), ('1', '♡'), ('8', '♡'), ('10', '♡'), ('9', '♠'), ('K', '♢'), ('5', '♢'), ('8', '♠'), ('Q', '♡'), ('10', '♢'), ('9', '♡'), ('9', '♢'), ('K', '♡'), ('5', '♣'), ('K', '♠'), ('8', '♢'), ('4', '♣'), ('2', '♡'), ('2', '♣'), ('10', '♣'), ('7', '♠'), ('1', '♠'), ('J', '♠'), ('7', '♣'), ('J', '♢'), ('3', '♠'), ('4', '♡'), ('3', '♡'), ('6', '♢'), ('6', '♡'), ('3', '♢'), ('Q', '♢'), ('9', '♣'), ('Q', '♠'), ('2', '♢'), ('8', '♣'), ('5', '♠'), ('10', '♠'), ('Q', '♣'), ('4', '♠'), ('J', '♡'), ('5', '♡'), ('4', '♢'), ('J', '♣'), ('1', '♢'), ('6', '♠'), ('1', '♣')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [33]:
# Місце для Вашого коду
list8=[10,50,100,250,500,1000,2500,5000,10000]
par=(2, 4, 6, 8, 10) 
for i in list8:
    n=0
    for j in range(i):
         
        np.random.shuffle(Cards)
        card=Cards[0]
        if i==10:print(card)
        try:
            if int(card[0]) in par:
                n+=1
        except Exception:
            pass
            
    print(i, n, n/i)

('2', '♢')
('9', '♡')
('10', '♡')
('10', '♢')
('4', '♠')
('5', '♢')
('5', '♠')
('5', '♢')
('2', '♠')
('4', '♣')
10 6 0.6
50 20 0.4
100 38 0.38
250 105 0.42
500 189 0.378
1000 369 0.369
2500 946 0.3784
5000 1923 0.3846
10000 3820 0.382


### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [34]:
# Місце для Вашого коду
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
heart = [(Rank,'♡') for Rank in Ranks]
diamonds= [(Rank,'♢') for Rank in Ranks]
clubs=[(Rank,'♣') for Rank in Ranks]
pikes=[(Rank,'♠') for Rank in Ranks]
All_suits=[heart, diamonds, clubs, pikes]
player1=[]
player2=[]
player3=[]
player4=[]
for j in All_suits:
   
    np.random.shuffle(j)
    for k in range (0, 3):
        player1.append(str(j[k]))
        player2.append(str(j[k+3]))
        player3.append(str(j[k+6]))
        player4.append(str(j[k+9]))
    np.random.shuffle([heart, diamonds, clubs, pikes])


tabble=[player1, player2, player3, player4]
q=0
for i in tabble:
    i.append(All_suits[q][12])
    q+=1
    print('player'+str(q), i)


player1 ["('8', '♡')", "('2', '♡')", "('K', '♡')", "('4', '♢')", "('10', '♢')", "('5', '♢')", "('J', '♣')", "('9', '♣')", "('10', '♣')", "('8', '♠')", "('5', '♠')", "('J', '♠')", ('9', '♡')]
player2 ["('J', '♡')", "('Q', '♡')", "('7', '♡')", "('9', '♢')", "('2', '♢')", "('3', '♢')", "('1', '♣')", "('8', '♣')", "('2', '♣')", "('4', '♠')", "('3', '♠')", "('1', '♠')", ('K', '♢')]
player3 ["('10', '♡')", "('3', '♡')", "('6', '♡')", "('8', '♢')", "('J', '♢')", "('6', '♢')", "('5', '♣')", "('6', '♣')", "('7', '♣')", "('7', '♠')", "('K', '♠')", "('9', '♠')", ('4', '♣')]
player4 ["('1', '♡')", "('5', '♡')", "('4', '♡')", "('7', '♢')", "('1', '♢')", "('Q', '♢')", "('Q', '♣')", "('K', '♣')", "('3', '♣')", "('10', '♠')", "('2', '♠')", "('6', '♠')", ('Q', '♠')]


### 5.4 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав від 2 до 5 карт кожної масті. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♣7, ♢K, ♡9, ♡1, ♡5}.

In [36]:
# Місце для Вашого коду

Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
heart = [(Rank,'♡') for Rank in Ranks]
diamonds= [(Rank,'♢') for Rank in Ranks]
clubs=[(Rank,'♣') for Rank in Ranks]
pikes=[(Rank,'♠') for Rank in Ranks]
All_suits=[heart, diamonds, clubs, pikes]
player1=[]
player2=[]
player3=[]
player4=[]
other=[]
for j in All_suits:
   
    np.random.shuffle(j)
    for k in range (0, 2):
        player1.append(str(j[k]))
        player2.append(str(j[k+2]))
        player3.append(str(j[k+4]))
        player4.append(str(j[k+6]))
    for k in range (8, 13):
        other.append(str(j[k]))
Flag=False
chance=0
while Flag==False:
    chance+=1
    Flag=True
    np.random.shuffle(other)
    l1=other[0:5]
    bubn=0
    tref=0
    pik=0
    cherv=0
    for j in l1:
        if j[0]=='♠':
            pik+=1
        elif j[0]=='♣':
            tref+=1
        elif j[0]=='♢':
            bubn+=1
        elif j[0]=='♡':
            cherv+=1
    if max(pik, cherv, bubn, tref)>3:
        Flag=False
        continue
    l2=other[5:10]
    bubn=0
    tref=0
    pik=0
    cherv=0
    for j in l2:
        if j[0]=='♠':
            pik+=1
        elif j[0]=='♣':
            tref+=1
        elif j[0]=='♢':
            bubn+=1
        elif j[0]=='♡':
            cherv+=1
    if max(pik, cherv, bubn, tref)>3:
        Flag=False
        continue
    l3=other[10:15]
    bubn=0
    tref=0
    pik=0
    cherv=0
    for j in l3:
        if j[0]=='♠':
            pik+=1
        elif j[0]=='♣':
            tref+=1
        elif j[0]=='♢':
            bubn+=1
        elif j[0]=='♡':
            cherv+=1
    if max(pik, cherv, bubn, tref)>3:
        Flag=False
        continue
    l4=other[15:20]
    bubn=0
    tref=0
    pik=0
    cherv=0
    for j in l4:
        if j[0]=='♠':
            pik+=1
        elif j[0]=='♣':
            tref+=1
        elif j[0]=='♢':
            bubn+=1
        elif j[0]=='♡':
            cherv+=1
            
    if max(pik, cherv, bubn, tref)>3:
        Flag=False
        continue


print('chance', chance)
for k in range (0, 5):
        player1.append(str(l1[k]))
        player2.append(str(l2[k]))
        player3.append(str(l3[k]))
        player4.append(str(l4[k]))

tabble=[player1, player2, player3, player4]
q=0
ind=[8, 8, 8, 8]
for i in tabble:
    #for ii in range(0,4):
        #low = 0
        #high = min(13-len(tabble[q]), 13-ind[ii], 3)+1
        #size = 1
        #alpha=int(np.random.randint(low=low, high=high, size=size))
        #if ii==3:
        #    alpha=high
        #print(alpha)
        #for iii in range(ind[ii], ind[ii]+alpha):
        #    i.append(All_suits[ii][iii])
        #ind[ii]+=alpha
    #take1=
    
    #i.append(All_suits[q][12])
    q+=1
    print('player'+str(q), i)


chance 1
player1 ["('2', '♡')", "('10', '♡')", "('2', '♢')", "('1', '♢')", "('10', '♣')", "('1', '♣')", "('8', '♠')", "('Q', '♠')", "('J', '♠')", "('8', '♣')", "('10', '♢')", "('3', '♣')", "('9', '♡')"]
player2 ["('1', '♡')", "('8', '♡')", "('Q', '♢')", "('4', '♢')", "('7', '♣')", "('9', '♣')", "('4', '♠')", "('1', '♠')", "('8', '♢')", "('7', '♡')", "('9', '♢')", "('5', '♡')", "('6', '♠')"]
player3 ["('K', '♡')", "('6', '♡')", "('3', '♢')", "('5', '♢')", "('6', '♣')", "('2', '♣')", "('K', '♠')", "('2', '♠')", "('6', '♢')", "('Q', '♡')", "('3', '♠')", "('J', '♣')", "('J', '♢')"]
player4 ["('4', '♡')", "('J', '♡')", "('7', '♢')", "('K', '♢')", "('5', '♣')", "('4', '♣')", "('10', '♠')", "('5', '♠')", "('K', '♣')", "('7', '♠')", "('9', '♠')", "('Q', '♣')", "('3', '♡')"]
